on: [push]
jobs:
  test:
    runs-on: codeberg-tiny

    steps:
      - run: echo "hello"
      - uses:  https://code.forgejo.org/actions/checkout@v3
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv python pin 3.10

      - name: Install dependencies
        run: uv sync 

      - name: Run checks
        run: |
          uv run make check
