on: [push]
jobs:
  test:
    runs-on: codeberg-tiny
    strategy:
      fail-fast: false
      matrix:
        configs:
          - { polars-version: "1.3", python: "3.8" }
          - { polars-version: "1.3",  python: "3.11" }
          - { polars-version: "1.3", python: "3.13" }
        # polars-version: ["1.1", "1.2", "1.37", "latest"]


    steps:
      - uses:  https://code.forgejo.org/actions/checkout@v3
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv python pin '${{ matrix.python-version }}'

      - name: Install dependencies
        run: uv sync 

      - name: Run checks
        run: |
          uv run make check
